# Generated by Django 5.2.8 on 2025-11-20 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=64, unique=True)),
                ('preferred_model', models.CharField(default='rag_main', max_length=50)),
                ('language', models.CharField(default='zh-TW', max_length=10)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('in_feedback_mode', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Line_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CS_App.lineuser')),
            ],
        ),
    ]
